# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- .jekyll-cache

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: "https://jbajic.com"
baseurl: ""
encoding: utf-8
lang: en-US
logo: /images/logos/l_as_logo.png
title: "Jure Bajic 2023"
description: "This is my website where I write about stuff I am interested"
permalink: pretty
logo: "/images/jure.png"
github_username: jbajic
email: "jure.bajic94@gmail.com"

# Pagination
paginate: 5
paginate_path: blog/page:num
author: Jure Bajic
social:
  name: Jure Bajic
  links:
  - https://github.com/jbajic
  - https://www.linkedin.com/in/jure-baji%C4%87-b1a60410b/


# Header nav
navigation_header:
- title: Home
  url: /
- title: About me
  url: /about_me/
- title: Blog
  url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: ""
    output: true
    description: ""
    feature_image: "/images/blog.png"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  LinkedIn: https://www.linkedin.com/in/jure-baji%C4%87-b1a60410b/
  GitHub: https://github.com/jbajic
  link: https://jbajic.com

